### ISSUE TITLE
Document behavior of CTRL^C

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#585]
I did a CTRL^C on a simulation and it killed the simulation (as expected, I guess)

```
INFO:absl:Task ID: 1694681833730783761
INFO:absl:Creating input archive...
INFO:absl:Input archive created.
INFO:absl:Input archive size: 27.76 KiB
INFO:absl:Uploading input...
INFO:absl:Input archive uploaded.
INFO:absl:Task request submitted.
INFO:absl:Waiting for resources...
INFO:absl:The task is being executed remotely.
^CINFO:absl:Caught SIGINT: terminating blocking task...
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    task = scenario.simulate(simulation_time=100, output_time_step=1)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/coastal/coastal_area.py", line 120, in simulate
    task = super().simulate(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/scenarios.py", line 53, in simulate
    return simulator.run(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/simulators/swash.py", line 32, in run
    return super().run(input_dir,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/simulators/simulator.py", line 58, in run
    return tasks.run_simulation(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/tasks/run_simulation.py", line 42, in run_simulation
    task.wait()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/inductiva/tasks/task.py", line 173, in wait
    time.sleep(polling_period)
KeyboardInterrupt
^C
```
It would be great to document this behaviour somewhere in the docs.
Should it be on the Task Managment section (FAQ)?

Also, should we have a way of allowing CTRL^C not to kill the task? (not for now, but I wonder if that can also be a useful behaviour.)

**Comment by IvanPombo** [comment]
Extra to the last part of what Sarmento mentions, we could have a CTRL^something so that simulations are not killed but we pass from sync to async mode :) That would be could just to check if everything is okay in the first minutes and then leave it be!
